# AIM ---------------------------------------------------------------------
# explore the barcodes and provide a consensus file for both

# lirbaries ---------------------------------------------------------------
library(tidyverse)
library(UpSetR)

# read in the data --------------------------------------------------------
# define the main folder of the dataset
folder <- "../../cellranger/cellranger7/output/Unsorted/outs/"

# read in the barcodes extracted from the bam files (pure intronic, pure exonic and exonic+intronic)
barcodes_exon <- read_tsv(paste0(folder,"cell_barcodes_exon.txt"),col_names = F)
barcodes_intron <- read_tsv(paste0(folder,"cell_barcodes_intron.txt"),col_names = F)
barcodes_all <- read_tsv(paste0(folder,"cell_barcodes_all.txt"),col_names = F)

# Francesca also provided the cleaned object from this dataset.
# extract the list of barcodes also from the pure objects
sobj <- readRDS("/beegfs/scratch/ric.cosr/ric.cosr/CRtest_genova_pedrini/raw_data/seu_obj/Unsorted.rds")

# wrangling ---------------------------------------------------------------
# set up a list of the barocdes
list_barcodes <- list(exon = barcodes_exon$X1,
                      intron = barcodes_intron$X1,
                      all = barcodes_all$X1)

# show the intersections of the barcodes
pdf("../out/plot/UpSet_common_barcodes_Unsorted.pdf", onefile=FALSE)
upset(fromList(list_barcodes), order.by = "freq")
dev.off()

# barcodes_common <- intersect(barcodes_exon$X1,barcodes_intron$X1)
# reduce(list(letters,letters[1:10],letters[5:15]),intersect)
barcodes_common <- purrr::reduce(list_barcodes,intersect)

# save the barcodes in common in a file
data.frame(barcodes_common) %>%
  write_tsv(paste0(folder,"cell_barcodes_common.txt"),col_names = F)

# save the table also in the project output folder as reference
data.frame(barcodes_common) %>%
  write_tsv("../out/table/cell_barcodes_common_Unsorted.txt",col_names = F)

# confirm the structure of the output
readLines(paste0(folder,"cell_barcodes_intron.txt"),n = 10)
readLines("../out/table/cell_barcodes_common_Unsorted.txt",n = 10)

# extract the barcodes from the seurat file
barcodes_seurat <- rownames(sobj@meta.data) %>%
  # add the labeles needed to uniform the barcode names
  paste0("CB:Z:",.,"-1")

# verify that all the barcodes extracted from the Seurat object are included in the cell_barcodes_all.txt
df1 <- data.frame("cell_barcode_seurat" = barcodes_seurat) %>%
  mutate(test_all = cell_barcode_seurat %in% barcodes_all$X1)

# some of the cell barcodes from the seurat object are missing in the barcodes extracted from the cellranger reanalysis
# maybe the cellranger run generated by Francesca was a different version?
df1 %>%
  filter(test_all ==F)

# to avoid any issue save the tabel without the missing barcodes
dim(df1)

# save the filtered barcodes extracteted from the seurat object in common in a file
# remember to add the labels to the barcodes 
df1 %>%
  filter(test_all == T) %>%
  pull(cell_barcode_seurat) %>%
  data.frame(.) %>%
  write_tsv(paste0(folder,"cell_barcodes_common_seurat.txt"),col_names = F)

# save it as reference in the output folder
df1 %>%
  filter(test_all == T) %>%
  pull(cell_barcode_seurat) %>%
  data.frame(.) %>%
  write_tsv("../out/table/cell_barcodes_common_seurat_Unsorted.txt",col_names = F)
